name: Set up Node.js
description: Checkout repository and set up Node.js
inputs:
  fetch-depth:
    description: Number of commits to fetch
    required: false
    default: "1"
  node-version:
    description: Node.js version
    required: false
    default: "22"
  npm-registry:
    description: npm registry URL
    required: false
  npm-scope:
    description: npm registry scope
    required: false
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
    - name: Set up Node.js
      uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.npm-registry }}
        scope: ${{ inputs.npm-scope }}
