default: true
extends: null
MD001: true
MD002:
  level: 1
MD003:
  style: "atx"
MD004:
  style: "dash"
MD005: true
MD006: true
MD007:
  indent: 3
  start_indented: false
  start_indent: 2
MD009:
  br_spaces: 2
  list_item_empty_lines: false
  strict: false
MD010:
  code_blocks: true
  ignore_code_languages: [ ]
  spaces_per_tab: 1
MD011: true
MD012:
  maximum: 1
MD013:
  line_length: 80
  heading_line_length: 80
  code_block_line_length: 80
  code_blocks: true
  tables: false
  headings: true
  headers: true
  strict: false
  stern: false
MD014: true
MD018: true
MD019: true
MD020: true
MD021: true
MD022:
  lines_above: 1
  lines_below: 1
MD023: true
MD024:
  allow_different_nesting: true
  siblings_only: true
MD025:
  level: 1
  front_matter_title: "^\\s*title\\s*[:=]"
MD026:
  punctuation: ".,;:!。，；：！"
MD027: true
MD028: true
MD029:
  style: "ordered"
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1
MD031:
  list_items: true
MD032: true
MD033:
  allowed_elements: [ ]
MD034: true
MD035:
  style: "---"
MD036:
  punctuation: ".,;:!?。，；：！？"
MD037: true
MD038: true
MD039: true
MD040: true
MD041:
  level: 1
  front_matter_title: "^\\s*title\\s*[:=]"
MD042: true
MD044:
  names: [ ]
  code_blocks: true
  html_elements: true
MD045: true
MD046:
  style: "fenced"
MD047: true
MD048:
  style: "backtick"
MD049:
  style: "underscore"
MD050:
  style: "asterisk"
MD051: true
MD052: true
MD053:
  ignored_definitions: [
    "//"
  ]
