name: Build Docker Container
description: Build Docker container and push to Azure container registry

inputs:
  registry-name:
    description: Name of the acr registry
    required: true
  tag-name:
    description: Name of the image tag
    required: true
  docker-context:
    description: Path to the build context
    required: false
    default: "."
  docker-file:
    description: Path to the dockerfile
    required: false
    default: "./Dockerfile"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to ACR
        uses: docker/login-action@v3
        with:with:
          registry: ${{ inputs.registry-name }}.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ inputs.tag-name }}
          context: ${{ inputs.docker-context }}
          file: ${{ inputs.docker-file }}
